# 配置Tomcat端口号
server:
  port: 9997
# 配置Spring Boot项目名
spring:
  application:
    name: xmall-admin
# 配置Dubbo信息
  dubbo:
    application:
      name: xmall-admin
    protocol:
      name: dubbo
      port: 20880
    registry:
      address: zookeeper://localhost:2181
    scan: com.augustars.xmall
# 配置视图解析器的前后缀
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp